### ISSUE TITLE
Unable to run GetAllElements operation with summarisation

### ISSUE THREAD

**Issue by p013570** [GovernmentCommunicationsHeadquarters/Gaffer#271]
If you run a GetAllElements operation with the summarise flag set to true an exception is thrown in in the operation handler:

```
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at gaffer.accumulostore.operation.handler.GetAllElementsHandler.doOperation(GetAllElementsHandler.java:52)
```

**Comment by p013570** [comment]
Merged into develop.
