### ISSUE TITLE
Trouble facing while running example programs of Gaffer

### ISSUE THREAD

**Issue by pranita-s** [GovernmentCommunicationsHeadquarters/Gaffer#54]
Hi, I have built Gaffer and Accumulo in Ubuntu.
Building of jar file of example is successful. I put example-0.3.1-SNAPSHOT.jar in accumulo/lib/ext
Then, I tried running it to see its exact working by entering command -- 
 $ bin/accumulo gaffer.example.SimpleQuery

but I am getting following error --

ubuntu@ip-172-31-24-17:~/Downloads/installs/accumulo-1.6.4$ bin/accumulo gaffer.example.SimpleQuery
java.lang.NoClassDefFoundError: gaffer/data/generator/ElementGenerator
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2625)
        at java.lang.Class.getMethod0(Class.java:2866)
        at java.lang.Class.getMethod(Class.java:1676)
        at org.apache.accumulo.start.Main.main(Main.java:115)
Caused by: java.lang.ClassNotFoundException: gaffer.data.generator.ElementGenerator
        at org.apache.commons.vfs2.impl.VFSClassLoader.findClass(VFSClassLoader.java:175)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        ... 5 more
gaffer.example.SimpleQuery must implement a public static void main(String args[]) method

What am I missing ?

**Comment by pranita-s** [comment]
Hi, It will be great if I could get help for the above error as I am stuck and not able to resolve it and write further client codes.
Thanks in advance .
